name: Deploy ReLED

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run deploy script on Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: bash /home/piani/hdd/reLED/deploy.sh
