name: Deploy ReLED

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Pi
    runs-on: self-hosted

    steps:
      - name: Run deploy script
        run: bash /home/piani/hdd/reLED/deploy.sh
